name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Ensure required Gradle files are present
      run: |
        if [ ! -f "build.gradle" ] || [ ! -f "settings.gradle" ]; then
          echo "Required Gradle files are missing. Please ensure that both build.gradle and settings.gradle are present in the root directory."
          exit 1
        fi

    - name: Ensure actual gradlew file is present
      run: |
        if [ ! -f "gradlew" ]; then
          echo "gradlew file is missing. Please ensure that the gradlew file is present in the root directory."
          exit 1
        fi

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run the project
      run: ./gradlew run

    - name: Run unit tests
      run: ./gradlew test

    - name: Notify on success
      if: success()
      run: echo "Build succeeded! Notifying stakeholders..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify on failure
      if: failure()
      run: echo "Build failed! Notifying stakeholders..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
